name: First workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress-Run
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Uploading artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 90

      - name: Deploy to git hub pages
        if: always()  
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: cypress/reports/html

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Cypress Test Results"
          SLACK_MESSAGE: |
            'Cypress execution report artifact: [Download Cypress Report](${{ steps.upload-artifact.outputs.uploaded-path }})'
            'GitHub Pages URL: https://${{ github.actor }}.github.io/${{ github.event.repository.name  }}'
