name: First workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress-Run
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run 

      - name: Uploading artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 90

      - name: Parse Cypress Results
        id: parse-results
        run: echo "::set-output name=status::$(cat cypress/results/output.json | jq -r '.totalTests, .totalPassed, .totalFailed')"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Cypress Test Results"
          SLACK_MESSAGE: |
            'Cypress execution report artifact: [Download Cypress Report](${{ steps.upload-artifact.outputs.uploaded-path }})'
            'Test Status: ${{ steps.parse-results.outputs.status }}'
