name: First try in dynamic workflows

on:
  push:
    branches: -main
  workflow_dispatch:

jobs:
  firstperf:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - name: run performance
        run: echo "Performance tests run"
        shell: bash

  secondperf:
    runs-on: ubuntu_latest
    steps:
      - name: runexitperformance
        run: echo "exited from the performance test "
        shell: bash
